### ISSUE TITLE
Extension does not work (for me), possible fix

### ISSUE THREAD

**Issue by Jaaap** [EmilyBonar/SearchBlocker#2]
This extension does not work for me in Firefox 128.0b4 - but i have many extensions and many weird settings.

What _does_ work is something like this (in `searchblock.js`):
```js
function hideBlocked() {
	browser.storage.local.get("domains").then((storageObj) => {
		for (let domain of storageObj.domains)
		{
			for (let a of document.querySelectorAll('a[href*="' + domain + '"]'))
			{
				a.parentNode.parentNode.style.opacity = 0.2;
			}
		}
	});
}
```

**Comment by emily-roses** [comment]
Thanks for letting me know! I just uploaded version 2.0 to Mozilla Addons, so it should hopefully be available shortly.
